# report_generator.py
import io
from datetime import datetime
from typing import Dict, Any, List, Optional
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.graphics.shapes import Drawing, Rect, Line, String, Circle, Group, Path

class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#64748B"))
       
        if self._pageNumber > 1:
            self.drawString(54, 750, "PYMUDCEMENT OPTIMA PRO v5.0 — TECHNICAL COMPLIANCE REPORT")
            self.setStrokeColor(colors.HexColor("#CBD5E1"))
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)
           
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(1)
        self.line(54, 45, 558, 45)
       
        self.drawString(54, 32, "Generated by: PyMudCement Optima Pro v5.0")
        self.drawCentredString(306, 32, "CONFIDENTIAL — DRILLING ENGINEERING DIVISION")
        self.drawRightString(558, 32, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()

def create_pressure_window_chart() -> Drawing:
    d = Drawing(450, 140)
    d.add(Rect(0, 0, 450, 140, fillColor=colors.HexColor("#F8FAFC"), strokeColor=colors.HexColor("#E2E8F0")))
    for x in range(50, 450, 50):
        d.add(Line(x, 10, x, 130, strokeColor=colors.HexColor("#E2E8F0"), strokeWidth=0.5))
    d.add(Rect(60, 10, 100, 120, fillColor=colors.HexColor("#FEE2E2"), strokeColor=colors.transparent))
    d.add(Rect(320, 10, 100, 120, fillColor=colors.HexColor("#FEE2E2"), strokeColor=colors.transparent))
    d.add(Rect(160, 10, 160, 120, fillColor=colors.HexColor("#DCFCE7"), strokeColor=colors.transparent))
    d.add(Line(200, 130, 220, 90, strokeColor=colors.HexColor("#2563EB"), strokeWidth=2))
    d.add(Line(220, 90, 210, 50, strokeColor=colors.HexColor("#2563EB"), strokeWidth=2))
    d.add(Line(210, 50, 235, 10, strokeColor=colors.HexColor("#2563EB"), strokeWidth=2))
    d.add(String(70, 115, "Pore Pressure", fontName="Helvetica-Bold", fontSize=8, fillColor=colors.HexColor("#991B1B")))
    d.add(String(190, 115, "ECD Operating Window", fontName="Helvetica-Bold", fontSize=8, fillColor=colors.HexColor("#166534")))
    d.add(String(330, 115, "Fracture Limit", fontName="Helvetica-Bold", fontSize=8, fillColor=colors.HexColor("#991B1B")))
    return d

def generate_pdf_payload(
    project_metadata: Dict[str, Any],
    physics_results: Dict[str, Any],
    diagnostic_results: Dict[str, Any],
    engineer_name: str = "Peter Prempeh"
) -> io.BytesIO:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, leftMargin=54, rightMargin=54, topMargin=54, bottomMargin=64)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle('CompTitle', fontName='Helvetica-Bold', fontSize=22, leading=26, textColor=colors.HexColor('#0F172A'))
    subtitle_style = ParagraphStyle('CompSub', fontName='Helvetica', fontSize=11, leading=15, textColor=colors.HexColor('#F97316'), spaceAfter=12)
    h1_style = ParagraphStyle('SectH1', fontName='Helvetica-Bold', fontSize=13, leading=17, textColor=colors.HexColor('#0F172A'), spaceBefore=14, spaceAfter=6)
    body_style = ParagraphStyle('SectBody', fontName='Helvetica', fontSize=9, leading=13, textColor=colors.HexColor('#334155'))
    bold_body = ParagraphStyle('SectBodyBold', fontName='Helvetica-Bold', fontSize=9, leading=13, textColor=colors.HexColor('#1E293B'))

    elements = [
        Paragraph("PYMUDCEMENT OPTIMA PRO v5.0", title_style),
        Paragraph("Engineering Technical Compliance Field Report", subtitle_style),
    ]

    # Meta Table
    meta_data = [
        [Paragraph("<b>Project Asset Base:</b>", body_style), Paragraph(str(project_metadata.get('name', 'N/A')), body_style), Paragraph("<b>Rig Identification:</b>", body_style), Paragraph(str(project_metadata.get('rig_name', 'Rig-05')), body_style)],
        [Paragraph("<b>Wellbore Depth:</b>", body_style), Paragraph(f"{physics_results.get('total_depth_ft', 0.0)} ft MD", body_style), Paragraph("<b>Lead Field Engineer:</b>", body_style), Paragraph(engineer_name, body_style)],
        [Paragraph("<b>Operating Client:</b>", body_style), Paragraph(str(project_metadata.get('company', 'Enterprise Hydrocarbons Corp')), body_style), Paragraph("<b>Report Identifier:</b>", body_style), Paragraph(f"PMC-{datetime.now().strftime('%M%S')}", body_style)],
        [Paragraph("<b>Flow Rate:</b>", body_style), Paragraph(f"{physics_results.get('flow_rate_gpm', 0.0)} GPM", body_style), Paragraph("<b>Date / Local Time:</b>", body_style), Paragraph(datetime.now().strftime('%Y-%m-%d / %H:%M'), body_style)],
    ]
    t_meta = Table(meta_data, colWidths=[110, 140, 110, 140])
    t_meta.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#E2E8F0')),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#F1F5F9')),
        ('TOPPADDING', (0,0), (-1,-1), 5),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
    ]))
    elements.extend([t_meta, Spacer(1, 10)])

    # Executive Summary Box
    severity = diagnostic_results.get("severity", "GREEN")
    status_text = "✔ STABLE OPERATIONAL GRADIENT" if severity == "GREEN" else ("⚠️ WARNING ELEVATED" if severity == "YELLOW" else "❌ CRITICAL BREACH")
   
    summary_box = [
        [Paragraph("<b>Well Health Status:</b>", body_style), Paragraph(status_text, bold_body)],
        [Paragraph("<b>Matched Hazard Vector:</b>", body_style), Paragraph(diagnostic_results.get("matched_hazard", "None"), body_style)],
        [Paragraph("<b>AI Diagnosis:</b>", body_style), Paragraph(diagnostic_results.get("detailed_diagnosis", "Nominal"), body_style)]
    ]
    t_summary = Table(summary_box, colWidths=[140, 360])
    t_summary.setStyle(TableStyle([
        ('BOX', (0,0), (-1,-1), 1.5, colors.HexColor('#0F172A')),
        ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#F1F5F9')),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
    ]))
    elements.extend([Paragraph("EXECUTIVE SUMMARY", h1_style), t_summary, Spacer(1, 10)])

    # Physics Table
    elements.append(Paragraph("1. Primary Mechanical Hydraulics Summary", h1_style))
    ecd = physics_results.get("equivalent_circulating_density_ecd_ppg", 0.0)
    spp = physics_results.get("standpipe_pressure_spp_psi", 0.0)
   
    comp_rows = [
        [Paragraph("<b>Metric Parameter</b>", bold_body), Paragraph("<b>Value Output</b>", bold_body), Paragraph("<b>Safe Limit</b>", bold_body), Paragraph("<b>Status</b>", bold_body)],
        [Paragraph("Equivalent Circulating Density (ECD)", body_style), Paragraph(f"{ecd:.2f} ppg", body_style), Paragraph("< 15.5 ppg", body_style), Paragraph("PASS" if ecd < 15.5 else "FAIL", bold_body)],
        [Paragraph("Standpipe Pressure (SPP)", body_style), Paragraph(f"{spp:.1f} psi", body_style), Paragraph("< 3500 psi", body_style), Paragraph("PASS" if spp < 3500 else "WARNING", bold_body)],
        [Paragraph("Annular Pressure Loss", body_style), Paragraph(f"{physics_results.get('total_annular_pressure_loss_psi', 0.0):.1f} psi", body_style), Paragraph("Dynamic", body_style), Paragraph("PASS", bold_body)],
        [Paragraph("Drillstring Pressure Loss", body_style), Paragraph(f"{physics_results.get('total_pipe_pressure_loss_psi', 0.0):.1f} psi", body_style), Paragraph("Dynamic", body_style), Paragraph("PASS", bold_body)],
    ]
    t_comp = Table(comp_rows, colWidths=[160, 110, 130, 100])
    t_comp.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#0F172A')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
        ('TOPPADDING', (0,0), (-1,-1), 5),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
    ]))
    elements.extend([t_comp, Spacer(1, 10)])

    # Visual Pressure Window Chart
    elements.append(Paragraph("2. Pressure Profile Visualization", h1_style))
    elements.append(create_pressure_window_chart())
    elements.append(Spacer(1, 15))

    # Recommendations & Signature Section
    elements.append(Paragraph("3. AI Action Blueprint & Engineering Sign-Off", h1_style))
    recs = diagnostic_results.get("actionable_recommendations", ["Maintain standard operations."])
    for rec in recs:
        elements.append(Paragraph(f"• {rec}", body_style))
   
    elements.append(Spacer(1, 20))
    sig_line = "_____________________________________"
    sig_data = [
        [Paragraph(f"<b>Prepared By:</b><br/><br/>{sig_line}<br/>Lead Engineer: {engineer_name}", body_style),
         Paragraph(f"<b>Approved By:</b><br/><br/>{sig_line}<br/>Rig Superintendent", body_style)]
    ]
    t_sig = Table(sig_data, colWidths=[250, 250])
    elements.append(t_sig)

    doc.build(elements, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer