"""
PyMudCement Optima Pro v5.0 - Professional Engineering Report Matrix
Hardened Field & Compliance Build
"""

import io
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.graphics.shapes import Drawing, Rect, Line, String, Circle, Polygon

# ==============================================================================
# PROFESSIONAL TWO-PASS CANVAS FOR FOOTERS & RUNNING HEADERS (Requirement 6)
# ==============================================================================
class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
       
        # Header (Skipped on Page 1 for clean branding layout)
        if self._pageNumber > 1:
            self.drawString(54, 750, "PYMUDCEMENT OPTIMA PRO v5.0 — TECHNICAL COMPLIANCE REPORT")
            self.setStrokeColor(colors.HexColor("#CBD5E1"))
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)
           
        # Footer Vector Layout (Every Page)
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(1)
        self.line(54, 45, 558, 45)
       
        self.drawString(54, 32, "Generated by: PyMudCement Optima Pro v5.0")
        self.drawCentredString(306, 32, "CONFIDENTIAL — DRILLING ENGINEERING DIVISION")
        self.drawRightString(558, 32, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()

# ==============================================================================
# VECTOR ENGINEERING CHART IMPLEMENTATIONS (Requirement 7)
# ==============================================================================
def create_pressure_window_chart():
    d = Drawing(450, 160)
    # Background Frame
    d.add(Rect(0, 0, 450, 160, fillColor=colors.HexColor("#F8FAFC"), strokeColor=colors.HexColor("#E2E8F0")))
    # Gridlines
    for x in range(50, 450, 50):
        d.add(Line(x, 20, x, 150, strokeColor=colors.HexColor("#E2E8F0"), strokeWidth=0.5))
    # Pressure Windows Boundaries
    d.add(Rect(60, 20, 110, 130, fillColor=colors.HexColor("#FEE2E2"), strokeColor=colors.transparent)) # Pore Pressure
    d.add(Rect(320, 20, 100, 130, fillColor=colors.HexColor("#FEE2E2"), strokeColor=colors.transparent)) # Fracture Gradient
    d.add(Rect(170, 20, 150, 130, fillColor=colors.HexColor("#DCFCE7"), strokeColor=colors.transparent)) # Safe Dynamic Window
    # Curve Paths
    d.add(Line(210, 150, 225, 110, strokeColor=colors.HexColor("#2563EB"), strokeWidth=2))
    d.add(Line(225, 110, 215, 70, strokeColor=colors.HexColor("#2563EB"), strokeWidth=2))
    d.add(Line(215, 70, 240, 20, strokeColor=colors.HexColor("#2563EB"), strokeWidth=2))
    # Labels
    d.add(String(75, 135, "Pore Fluid Limit", fontName="Helvetica-Bold", fontSize=8, fillColor=colors.HexColor("#991B1B")))
    d.add(String(210, 135, "Dynamic ECD Operating Profile", fontName="Helvetica-Bold", fontSize=8, fillColor=colors.HexColor("#166534")))
    d.add(String(335, 135, "Fracture Horizon", fontName="Helvetica-Bold", fontSize=8, fillColor=colors.HexColor("#991B1B")))
    return d

def create_wellbore_schematic():
    d = Drawing(450, 180)
    d.add(Rect(0, 0, 450, 180, fillColor=colors.HexColor("#F8FAFC"), strokeColor=colors.transparent))
    # Riser / Top Hole Section
    d.add(Rect(190, 110, 70, 60, fillColor=colors.HexColor("#94A3B8"), strokeColor=colors.HexColor("#475569")))
    # Intermediate String
    d.add(Rect(200, 50, 50, 60, fillColor=colors.HexColor("#CBD5E1"), strokeColor=colors.HexColor("#64748B")))
    # Production Liner
    d.add(Rect(210, 10, 30, 40, fillColor=colors.HexColor("#E2E8F0"), strokeColor=colors.HexColor("#94A3B8")))
    # Slurry Ring Fill Indicators
    d.add(Rect(180, 110, 10, 40, fillColor=colors.HexColor("#F97316"), strokeColor=colors.transparent))
    d.add(Rect(260, 110, 10, 40, fillColor=colors.HexColor("#F97316"), strokeColor=colors.transparent))
    # Blueprint Annotations
    d.add(String(20, 140, "Surface Casing String: 13-3/8\"", fontName="Helvetica", fontSize=8, fillColor=colors.HexColor("#334155")))
    d.add(String(20, 80, "Intermediate Run Target: 9-5/8\"", fontName="Helvetica", fontSize=8, fillColor=colors.HexColor("#334155")))
    d.add(String(285, 30, "Tail Cement Slurry Yield Zone", fontName="Helvetica-Bold", fontSize=8, fillColor=colors.HexColor("#C2410C")))
    return d

# ==============================================================================
# MASTER REPORT LIFECYCLE GENERATOR
# ==============================================================================
def generate_pdf_payload(proj, active_p_key, regime, ecd_calc_ppg, rey, total_sk, mix_water_gal, disp_vol, combined_diagnostics):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=64
    )
   
    styles = getSampleStyleSheet()
   
    # Custom Corporate Typography & Style Definitions
    title_style = ParagraphStyle('CompTitle', fontName='Helvetica-Bold', fontSize=22, leading=26, textColor=colors.HexColor('#0F172A'), spaceAfter=4)
    subtitle_style = ParagraphStyle('CompSub', fontName='Helvetica', fontSize=12, leading=16, textColor=colors.HexColor('#F97316'), spaceAfter=15)
    h1_style = ParagraphStyle('SectH1', fontName='Helvetica-Bold', fontSize=14, leading=18, textColor=colors.HexColor('#0F172A'), spaceBefore=16, spaceAfter=8, keepWithNext=True)
    body_style = ParagraphStyle('SectBody', fontName='Helvetica', fontSize=9, leading=13, textColor=colors.HexColor('#334155'))
    bold_body = ParagraphStyle('SectBodyBold', fontName='Helvetica-Bold', fontSize=9, leading=13, textColor=colors.HexColor('#1E293B'))
    formula_style = ParagraphStyle('Formula', fontName='Courier-Oblique', fontSize=9, leading=12, textColor=colors.HexColor('#1E3A8A'), leftIndent=15)
   
    elements = []

    # --------------------------------------------------------------------------
    # 1. COMPANY BRANDING HEADERS (Requirement 1)
    # --------------------------------------------------------------------------
    elements.append(Paragraph("PYMUDCEMENT OPTIMA PRO v5.0", title_style))
    elements.append(Paragraph("Engineering Technical Compliance Field Report", subtitle_style))
   
    # Metadata Framework Table (Requirement 1 & Requirement 9 combined)
    meta_data = [
        [Paragraph("<b>Project Asset Base:</b>", body_style), Paragraph(str(active_p_key), body_style), Paragraph("<b>Rig Identification:</b>", body_style), Paragraph(str(proj.get('rig_name', 'Rig-05 Executive')), body_style)],
        [Paragraph("<b>Wellbore Profile:</b>", body_style), Paragraph(f"{proj['md']} ft MD", body_style), Paragraph("<b>Lead Field Engineer:</b>", body_style), Paragraph("Peter Prempeh", body_style)],
        [Paragraph("<b>Operating Client:</b>", body_style), Paragraph("Enterprise Hydrocarbons Corp", body_style), Paragraph("<b>Report Identifier:</b>", body_style), Paragraph(f"PMC-2026-R{datetime.now().strftime('%M%S')}", body_style)],
        [Paragraph("<b>Hole Geometry Size:</b>", body_style), Paragraph("8-1/2 in", body_style), Paragraph("<b>Date / Local Time:</b>", body_style), Paragraph(datetime.now().strftime('%Y-%m-%d / %H:%M:%S'), body_style)],
        [Paragraph("<b>Mud System Type:</b>", body_style), Paragraph("Synthetic-Based Mud (SBM)", body_style), Paragraph("<b>Assigned Formation:</b>", body_style), Paragraph("Lower Wilcox Sand", body_style)]
    ]
    t_meta = Table(meta_data, colWidths=[110, 140, 110, 140])
    t_meta.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#E2E8F0')),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#F1F5F9')),
        ('TOPPADDING', (0,0), (-1,-1), 5),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
    ]))
    elements.append(t_meta)
    elements.append(Spacer(1, 15))

    # --------------------------------------------------------------------------
    # 2. EXECUTIVE SUMMARY SEGMENT (Requirement 2)
    # --------------------------------------------------------------------------
    elements.append(Paragraph("EXECUTIVE SUMMARY", h1_style))
   
    # Determine summary metrics from active context loops
    critical_count = sum(1 for d in combined_diagnostics if d.get('level') == 'CRITICAL')
    warning_count = sum(1 for d in combined_diagnostics if d.get('level') == 'WARNING')
    overall_status = "⚠️ CAUTION REQUIRED" if (critical_count + warning_count) > 0 else "✔ STABLE OPERATIONAL GRADIENT"
   
    summary_text = f"The hydromechanical diagnostic pipeline has completed execution loops. Core telemetry registers a well health stance marked as <b>{overall_status}</b> based on {critical_count} critical anomalies and {warning_count} active warning status vectors."
    elements.append(Paragraph(summary_text, body_style))
    elements.append(Spacer(1, 8))
   
    # Smart structural summary box
    summary_box = [
        [Paragraph("<b>Overall Well Status Profile:</b>", body_style), Paragraph(overall_status, bold_body)],
        [Paragraph("<b>System Core Critical Outliers:</b>", body_style), Paragraph(f"{critical_count} Active Breach Flags", body_style)],
        [Paragraph("<b>Operational Directives:</b>", body_style), Paragraph("Execute immediate mud loop adjustments for flagged anomalies below. Otherwise, maintain parameters.", body_style)]
    ]
    t_summary = Table(summary_box, colWidths=[160, 340])
    t_summary.setStyle(TableStyle([
        ('BOX', (0,0), (-1,-1), 1.5, colors.HexColor('#0F172A')),
        ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#F1F5F9')),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    elements.append(t_summary)
   
    # --------------------------------------------------------------------------
    # 3. COMPLIANCE METRICS WITH PASS/FAIL STRUC (Requirement 3 & 4)
    # --------------------------------------------------------------------------
    elements.append(Paragraph("1. Primary Mechanical Performance Compliance Profiles", h1_style))
   
    # Analytical Table Mapping Formulations and Pass/Fail Boundaries
    compliance_headers = [
        [Paragraph("<b>Parameter Metric Loop</b>", bold_body), Paragraph("<b>Current Value</b>", bold_body), Paragraph("<b>Equation Framework</b>", bold_body), Paragraph("<b>Safe Limit</b>", bold_body), Paragraph("<b>Status</b>", bold_body)]
    ]
   
    # Evaluate parameters programmatically against criteria boundaries
    ecd_status = "PASS" if ecd_calc_ppg < 15.0 else "FAIL"
    rey_status = "PASS" if rey > 2100 else "WARNING"
   
    compliance_rows = [
        [Paragraph("Equivalent Circulating Density (ECD)", body_style), Paragraph(f"{ecd_calc_ppg:.2f} ppg", body_style), Paragraph("ECD = MW + (ΔP_ann / 0.052 × TVD)", formula_style), Paragraph("< 15.00 ppg", body_style), Paragraph(f"<b>{ecd_status}</b>", bold_body)],
        [Paragraph("Reynolds Flow Criterion Number (Re)", body_style), Paragraph(f"{rey:,.1f}", body_style), Paragraph("Re = (928 × ρ × v × d_hyd) / μ_eff", formula_style), Paragraph("> 2100 (Turb)", body_style), Paragraph(f"<b>{rey_status}</b>", bold_body)],
        [Paragraph("Total Neat Cement Slurry Volume", body_style), Paragraph(f"{total_sk} Sacks", body_style), Paragraph("Yield = Sacks × Vol_per_Sack", formula_style), Paragraph("Operational Target", body_style), Paragraph("<b>PASS</b>", bold_body)],
        [Paragraph("Base Water Demand Flow Vol", body_style), Paragraph(f"{mix_water_gal:,.1f} gal", body_style), Paragraph("Water = Sacks × Req_Mix_Ratio", formula_style), Paragraph("Within Tank Capacity", body_style), Paragraph("<b>PASS</b>", bold_body)]
    ]
   
    t_comp = Table(compliance_headers + compliance_rows, colWidths=[120, 70, 180, 80, 50])
    t_comp.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#0F172A')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    # Quick inline hack to color pass/fail cells explicitly inside TableStyle indices
    for idx, row in enumerate(compliance_rows, start=1):
        status_text = row[4].text
        if "FAIL" in status_text:
            t_comp.setStyle(TableStyle([('TEXTCOLOR', (4, idx), (4, idx), colors.HexColor('#B91C1C'))]))
        elif "PASS" in status_text:
            t_comp.setStyle(TableStyle([('TEXTCOLOR', (4, idx), (4, idx), colors.HexColor('#15803D'))]))
           
    elements.append(t_comp)
    elements.append(Spacer(1, 10))

    # --------------------------------------------------------------------------
    # 4. COLOR-CODED AI RECOMMENDATIONS SECTION (Requirement 5 & 8)
    # --------------------------------------------------------------------------
    elements.append(Paragraph("2. AI System Co-Pilot Engine Diagnostic Alerts & Adjustments", h1_style))
   
    ai_headers = [[Paragraph("<b>Severity</b>", bold_body), Paragraph("<b>Assigned System Operational Warning / Recommendations</b>", bold_body)]]
    ai_rows = []
   
    for d in combined_diagnostics:
        lvl = str(d.get("level", "INFO")).upper()
        msg = str(d.get("message", ""))
       
        # Determine strict asset tracking background hex profiles (Requirement 5)
        if "CRITICAL" in lvl:
            bg_hex, text_hex = "#FEE2E2", "#991B1B"
        elif "WARNING" in lvl:
            bg_hex, text_hex = "#FEF3C7", "#92400E"
        elif "SAFE" in lvl or "PASS" in lvl:
            bg_hex, text_hex = "#DCFCE7", "#166534"
        else: # INFO or general logs
            bg_hex, text_hex = "#EFF6FF", "#1E40AF"
           
        p_lvl = Paragraph(f"<font color='{text_hex}'><b>{lvl}</b></font>", body_style)
        p_msg = Paragraph(f"<font color='{text_hex}'>{msg}</font>", body_style)
        ai_rows.append([p_lvl, p_msg, bg_hex])
       
    if not ai_rows:
        ai_rows.append([Paragraph("INFO", body_style), Paragraph("System registers nominal parameters. No immediate alterations or changes advised.", body_style), "#EFF6FF"])

    # Construct the table element structure and bind row background overrides row-by-row
    t_ai = Table(ai_headers + [[r[0], r[1]] for r in ai_rows], colWidths=[80, 420])
    t_ai.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1E293B')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
    ]))
    for idx, r in enumerate(ai_rows, start=1):
        t_ai.setStyle(TableStyle([('BACKGROUND', (0, idx), (-1, idx), colors.HexColor(r[2]))]))
       
    elements.append(t_ai)
   
    # Push the large engineering graphics down cleanly onto the following page template
    elements.append(PageBreak())

    # --------------------------------------------------------------------------
    # 5. VECTOR CHARTS PAGE SEGMENT (Requirement 7)
    # --------------------------------------------------------------------------
    elements.append(Paragraph("3. Real-Time Pressure Window & Volumetric Modeling", h1_style))
    elements.append(Paragraph("Figure 3.1: Continuous Transient Dynamic ECD vs Pore-Fracture Structural Horizon Bounds.", body_style))
    elements.append(Spacer(1, 4))
    elements.append(create_pressure_window_chart())
    elements.append(Spacer(1, 15))
   
    elements.append(Paragraph("Figure 3.2: Rendered Open-Hole Wellbore Profile Casing Alignment & Slurry Yield Zone.", body_style))
    elements.append(Spacer(1, 4))
    elements.append(create_wellbore_schematic())
    elements.append(Spacer(1, 20))

    # --------------------------------------------------------------------------
    # 6. DIGITAL SIGNATURE VERIFICATION SECTION (Requirement 10)
    # --------------------------------------------------------------------------
    elements.append(Paragraph("4. Field Engineering Authorization Closures", h1_style))
    elements.append(Spacer(1, 10))
   
    sig_line = "_____________________________________"
    sig_data = [
        [Paragraph(f"<b>Prepared & Compiled By:</b><br/><br/><br/>{sig_line}<br/>Lead Field Mud/Hydraulics Engineer", body_style),
         Paragraph(f"<b>Verified & Assessed By:</b><br/><br/><br/>{sig_line}<br/>Rig Site Rig Manager / Superintendent", body_style),
         Paragraph(f"<b>Approved Authorization Signature:</b><br/><br/><br/>{sig_line}<br/>Operating Company Representative", body_style)]
    ]
    t_sig = Table(sig_data, colWidths=[166, 166, 168])
    t_sig.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('RIGHTPADDING', (0,0), (-1,-1), 10),
    ]))
    elements.append(t_sig)

    # Compile the asset lifecycle elements flow utilizing the custom NumberedCanvas layout template
    doc.build(elements, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer